### ISSUE TITLE
Compound Colors not automatlebe through automated crafters.

### ISSUE THREAD

**Issue by linuxchr** [DarkPacks/SkyFactory-5#101]
### Bug Description

You cannon craft compund colors such as Green, Cyan, Purple ecetera in Automatic Crafters(EnderIO,RFToools, Thermal) as they are staged. I would suggest adding a not consumed color mixer(Custom Item added with ContentTweaker), for which
you need the color itself so progession is not broken.

### Did this behavior used to work in the previous version?

Unknown

### If you answered Yes above...

n. A

### Steps to Reproduce (for bugs)

n. A

### Client/Server Log:

n. A

### Crash Log:

n. A

### Modpack Version world created in:

5.0.2

### Additional Content Installed?

n. A

### Modpack Version:

5.0.2

### Java Version:

n. A

### Launcher Used:

n. A

### Memory Allocated:

n. A

### Single Player/LAN/Server:

Server

### Optifine Installed:

No

### Shaders Enabled:

No

**Comment by linuxchr** [comment]
Other suggestion to fix would be just staging the mixer(Custom Item) it self and not staging crafts with it.

**Comment by linuxchr** [comment]
Add a custom item that is staged. But Recipies with it are not staged. So you need to handcraft the mixer. But then you can put the mixer in to the autocrafter and have it autocraft stuff because these recipies are not staged.

**Comment by linuxchr** [comment]
Yeah, but the crafter can autocraft dyes

**Comment by linuxchr** [comment]
![Unbenannt](https://github.com/user-attachments/assets/f438cdc8-fa75-4da4-9315-bbdb1b2ced97)

**Comment by linuxchr** [comment]
![grafik](https://github.com/user-attachments/assets/38118d26-7db7-413d-90e0-bd93e6259ac5)

**Comment by linuxchr** [comment]
![grafik](https://github.com/user-attachments/assets/733a78b6-7fff-4b1d-9adc-35f514f04182)
But The infusuion crystal is a custom item and is staged, but the shown recipie is not staged

**Comment by linuxchr** [comment]
https://github.com/user-attachments/assets/6d3462f3-2c29-43cc-9bfd-04d769437c7c

**Comment by Darkosto** [comment]
Fixed via a new set of recipes that should within the pack staging

**Comment by Capybara121** [comment]
Could this issue be reopened? The fix here still doesn't perfectly work for standard ae2 autocrafter setups. I am aware that recursive crafting setups do exist in ae2 but it doesn't make sense to me that crafting compound dyes require them. Would it be possible to change the recipe to be non-recursive?
